site_name: NanoVM Docs

theme:
  name: material

nav:
  - Home: index.md

  - Assembly:
      - Instructions: assembly/instructions.md
      - Registers: assembly/registers.md

  - VM:
      - VM: vm/vm.md

  - Linker:
      - Linker: linker/linker.md
